// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
pub type CommandInput = uzimaru::echo::types::CommandInput;
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_run_cabi<T: Guest>(
    arg0: *mut u8,
    arg1: usize,
    arg2: *mut u8,
    arg3: usize,
    arg4: *mut u8,
    arg5: usize,
) -> i32 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let base3 = arg0;
    let len3 = arg1;
    let mut result3 = _rt::Vec::with_capacity(len3);
    for i in 0..len3 {
        let base = base3.add(i * (2 * ::core::mem::size_of::<*const u8>()));
        let e3 = {
            let l0 = *base.add(0).cast::<*mut u8>();
            let l1 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len2 = l1;
            let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);
            _rt::string_lift(bytes2)
        };
        result3.push(e3);
    }
    _rt::cabi_dealloc(
        base3,
        len3 * (2 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let base10 = arg2;
    let len10 = arg3;
    let mut result10 = _rt::Vec::with_capacity(len10);
    for i in 0..len10 {
        let base = base10.add(i * (4 * ::core::mem::size_of::<*const u8>()));
        let e10 = {
            let l4 = *base.add(0).cast::<*mut u8>();
            let l5 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len6 = l5;
            let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
            let l7 = *base
                .add(2 * ::core::mem::size_of::<*const u8>())
                .cast::<*mut u8>();
            let l8 = *base.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len9 = l8;
            let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
            (_rt::string_lift(bytes6), _rt::string_lift(bytes9))
        };
        result10.push(e10);
    }
    _rt::cabi_dealloc(
        base10,
        len10 * (4 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let len11 = arg5;
    let bytes11 = _rt::Vec::from_raw_parts(arg4.cast(), len11, len11);
    let result12 = T::run(uzimaru::echo::types::CommandInput {
        args: result3,
        env: result10,
        cwd: _rt::string_lift(bytes11),
    });
    _rt::as_i32(result12)
}
pub trait Guest {
    /// exit code のみを返す
    /// stdout/stderr は cargo-component が自動的に WASI imports を追加
    fn run(input: CommandInput) -> i32;
}
#[doc(hidden)]
macro_rules! __export_world_echo_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "run")] unsafe extern "C" fn
        export_run(arg0 : * mut u8, arg1 : usize, arg2 : * mut u8, arg3 : usize, arg4 : *
        mut u8, arg5 : usize,) -> i32 { unsafe { $($path_to_types)*::
        _export_run_cabi::<$ty > (arg0, arg1, arg2, arg3, arg4, arg5) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_echo_cabi;
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod uzimaru {
    pub mod echo {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct CommandInput {
                pub args: _rt::Vec<_rt::String>,
                pub env: _rt::Vec<(_rt::String, _rt::String)>,
                pub cwd: _rt::String,
            }
            impl ::core::fmt::Debug for CommandInput {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("CommandInput")
                        .field("args", &self.args)
                        .field("env", &self.env)
                        .field("cwd", &self.cwd)
                        .finish()
                }
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::string::String;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_echo_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_echo_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_echo_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:uzimaru:echo:echo:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 283] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xa0\x01\x01A\x02\x01\
A\x06\x01B\x05\x01ps\x01o\x02ss\x01p\x01\x01r\x03\x04args\0\x03env\x02\x03cwds\x04\
\0\x0dcommand-input\x03\0\x03\x03\0\x12uzimaru:echo/types\x05\0\x02\x03\0\0\x0dc\
ommand-input\x03\0\x0dcommand-input\x03\0\x01\x01@\x01\x05input\x02\0z\x04\0\x03\
run\x01\x03\x04\0\x11uzimaru:echo/echo\x04\0\x0b\x0a\x01\0\x04echo\x03\0\0\0G\x09\
producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rus\
t\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
