// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod uzimaru {
    pub mod shell {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// 環境変数参照
            #[derive(Clone)]
            pub struct EnvRef {
                pub name: _rt::String,
                pub default_value: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for EnvRef {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("EnvRef")
                        .field("name", &self.name)
                        .field("default-value", &self.default_value)
                        .finish()
                }
            }
            /// ワードセグメント
            #[derive(Clone)]
            pub enum WordSegment {
                Literal(_rt::String),
                EnvVar(EnvRef),
                CommandSubst(u32),
            }
            impl ::core::fmt::Debug for WordSegment {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        WordSegment::Literal(e) => {
                            f.debug_tuple("WordSegment::Literal").field(e).finish()
                        }
                        WordSegment::EnvVar(e) => {
                            f.debug_tuple("WordSegment::EnvVar").field(e).finish()
                        }
                        WordSegment::CommandSubst(e) => {
                            f.debug_tuple("WordSegment::CommandSubst").field(e).finish()
                        }
                    }
                }
            }
            /// パース済みワード
            #[derive(Clone)]
            pub struct ParsedWord {
                pub segments: _rt::Vec<WordSegment>,
            }
            impl ::core::fmt::Debug for ParsedWord {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ParsedWord")
                        .field("segments", &self.segments)
                        .finish()
                }
            }
            /// リダイレクト種別
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum RedirectKind {
                Stdin,
                Stdout,
                StdoutAppend,
            }
            impl ::core::fmt::Debug for RedirectKind {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        RedirectKind::Stdin => {
                            f.debug_tuple("RedirectKind::Stdin").finish()
                        }
                        RedirectKind::Stdout => {
                            f.debug_tuple("RedirectKind::Stdout").finish()
                        }
                        RedirectKind::StdoutAppend => {
                            f.debug_tuple("RedirectKind::StdoutAppend").finish()
                        }
                    }
                }
            }
            impl RedirectKind {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> RedirectKind {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => RedirectKind::Stdin,
                        1 => RedirectKind::Stdout,
                        2 => RedirectKind::StdoutAppend,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// リダイレクト
            #[derive(Clone)]
            pub struct Redirect {
                pub kind: RedirectKind,
                pub target: ParsedWord,
            }
            impl ::core::fmt::Debug for Redirect {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Redirect")
                        .field("kind", &self.kind)
                        .field("target", &self.target)
                        .finish()
                }
            }
            /// 単純コマンド
            #[derive(Clone)]
            pub struct SimpleCommand {
                pub args: _rt::Vec<ParsedWord>,
                pub redirects: _rt::Vec<Redirect>,
            }
            impl ::core::fmt::Debug for SimpleCommand {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("SimpleCommand")
                        .field("args", &self.args)
                        .field("redirects", &self.redirects)
                        .finish()
                }
            }
            /// パイプライン
            #[derive(Clone)]
            pub struct Pipeline {
                pub commands: _rt::Vec<SimpleCommand>,
            }
            impl ::core::fmt::Debug for Pipeline {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Pipeline").field("commands", &self.commands).finish()
                }
            }
            /// 条件接続子
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Connector {
                None,
                And,
                Or,
            }
            impl ::core::fmt::Debug for Connector {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Connector::None => f.debug_tuple("Connector::None").finish(),
                        Connector::And => f.debug_tuple("Connector::And").finish(),
                        Connector::Or => f.debug_tuple("Connector::Or").finish(),
                    }
                }
            }
            impl Connector {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Connector {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Connector::None,
                        1 => Connector::And,
                        2 => Connector::Or,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// 条件要素
            #[derive(Clone)]
            pub struct ConditionalElement {
                pub connector: Connector,
                pub pipeline: Pipeline,
            }
            impl ::core::fmt::Debug for ConditionalElement {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ConditionalElement")
                        .field("connector", &self.connector)
                        .field("pipeline", &self.pipeline)
                        .finish()
                }
            }
            /// コマンド置換
            #[derive(Clone)]
            pub struct CommandSubstitution {
                pub id: u32,
                pub input: _rt::String,
            }
            impl ::core::fmt::Debug for CommandSubstitution {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("CommandSubstitution")
                        .field("id", &self.id)
                        .field("input", &self.input)
                        .finish()
                }
            }
            /// パース結果
            #[derive(Clone)]
            pub struct ParseResult {
                pub elements: _rt::Vec<ConditionalElement>,
                pub substitutions: _rt::Vec<CommandSubstitution>,
            }
            impl ::core::fmt::Debug for ParseResult {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ParseResult")
                        .field("elements", &self.elements)
                        .field("substitutions", &self.substitutions)
                        .finish()
                }
            }
            /// パースエラー
            #[derive(Clone)]
            pub struct ParseError {
                pub message: _rt::String,
                pub position: u32,
            }
            impl ::core::fmt::Debug for ParseError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ParseError")
                        .field("message", &self.message)
                        .field("position", &self.position)
                        .finish()
                }
            }
            impl ::core::fmt::Display for ParseError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for ParseError {}
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod uzimaru {
        pub mod shell {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod parser {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ParseResult = super::super::super::super::uzimaru::shell::types::ParseResult;
                pub type ParseError = super::super::super::super::uzimaru::shell::types::ParseError;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_parse_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let result1 = T::parse(_rt::string_lift(bytes0));
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result1 {
                        Ok(e) => {
                            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
                            let super::super::super::super::uzimaru::shell::types::ParseResult {
                                elements: elements3,
                                substitutions: substitutions3,
                            } = e;
                            let vec25 = elements3;
                            let len25 = vec25.len();
                            let layout25 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec25.len() * (3 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result25 = if layout25.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout25).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout25);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec25.into_iter().enumerate() {
                                let base = result25
                                    .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let super::super::super::super::uzimaru::shell::types::ConditionalElement {
                                        connector: connector4,
                                        pipeline: pipeline4,
                                    } = e;
                                    *base.add(0).cast::<u8>() = (connector4.clone() as i32)
                                        as u8;
                                    let super::super::super::super::uzimaru::shell::types::Pipeline {
                                        commands: commands5,
                                    } = pipeline4;
                                    let vec24 = commands5;
                                    let len24 = vec24.len();
                                    let layout24 = _rt::alloc::Layout::from_size_align_unchecked(
                                        vec24.len() * (4 * ::core::mem::size_of::<*const u8>()),
                                        ::core::mem::size_of::<*const u8>(),
                                    );
                                    let result24 = if layout24.size() != 0 {
                                        let ptr = _rt::alloc::alloc(layout24).cast::<u8>();
                                        if ptr.is_null() {
                                            _rt::alloc::handle_alloc_error(layout24);
                                        }
                                        ptr
                                    } else {
                                        ::core::ptr::null_mut()
                                    };
                                    for (i, e) in vec24.into_iter().enumerate() {
                                        let base = result24
                                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                                        {
                                            let super::super::super::super::uzimaru::shell::types::SimpleCommand {
                                                args: args6,
                                                redirects: redirects6,
                                            } = e;
                                            let vec14 = args6;
                                            let len14 = vec14.len();
                                            let layout14 = _rt::alloc::Layout::from_size_align_unchecked(
                                                vec14.len() * (2 * ::core::mem::size_of::<*const u8>()),
                                                ::core::mem::size_of::<*const u8>(),
                                            );
                                            let result14 = if layout14.size() != 0 {
                                                let ptr = _rt::alloc::alloc(layout14).cast::<u8>();
                                                if ptr.is_null() {
                                                    _rt::alloc::handle_alloc_error(layout14);
                                                }
                                                ptr
                                            } else {
                                                ::core::ptr::null_mut()
                                            };
                                            for (i, e) in vec14.into_iter().enumerate() {
                                                let base = result14
                                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                                {
                                                    let super::super::super::super::uzimaru::shell::types::ParsedWord {
                                                        segments: segments7,
                                                    } = e;
                                                    let vec13 = segments7;
                                                    let len13 = vec13.len();
                                                    let layout13 = _rt::alloc::Layout::from_size_align_unchecked(
                                                        vec13.len() * (6 * ::core::mem::size_of::<*const u8>()),
                                                        ::core::mem::size_of::<*const u8>(),
                                                    );
                                                    let result13 = if layout13.size() != 0 {
                                                        let ptr = _rt::alloc::alloc(layout13).cast::<u8>();
                                                        if ptr.is_null() {
                                                            _rt::alloc::handle_alloc_error(layout13);
                                                        }
                                                        ptr
                                                    } else {
                                                        ::core::ptr::null_mut()
                                                    };
                                                    for (i, e) in vec13.into_iter().enumerate() {
                                                        let base = result13
                                                            .add(i * (6 * ::core::mem::size_of::<*const u8>()));
                                                        {
                                                            use super::super::super::super::uzimaru::shell::types::WordSegment as V12;
                                                            match e {
                                                                V12::Literal(e) => {
                                                                    *base.add(0).cast::<u8>() = (0i32) as u8;
                                                                    let vec8 = (e.into_bytes()).into_boxed_slice();
                                                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                                                    let len8 = vec8.len();
                                                                    ::core::mem::forget(vec8);
                                                                    *base
                                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                                        .cast::<usize>() = len8;
                                                                    *base
                                                                        .add(::core::mem::size_of::<*const u8>())
                                                                        .cast::<*mut u8>() = ptr8.cast_mut();
                                                                }
                                                                V12::EnvVar(e) => {
                                                                    *base.add(0).cast::<u8>() = (1i32) as u8;
                                                                    let super::super::super::super::uzimaru::shell::types::EnvRef {
                                                                        name: name9,
                                                                        default_value: default_value9,
                                                                    } = e;
                                                                    let vec10 = (name9.into_bytes()).into_boxed_slice();
                                                                    let ptr10 = vec10.as_ptr().cast::<u8>();
                                                                    let len10 = vec10.len();
                                                                    ::core::mem::forget(vec10);
                                                                    *base
                                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                                        .cast::<usize>() = len10;
                                                                    *base
                                                                        .add(::core::mem::size_of::<*const u8>())
                                                                        .cast::<*mut u8>() = ptr10.cast_mut();
                                                                    match default_value9 {
                                                                        Some(e) => {
                                                                            *base
                                                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<u8>() = (1i32) as u8;
                                                                            let vec11 = (e.into_bytes()).into_boxed_slice();
                                                                            let ptr11 = vec11.as_ptr().cast::<u8>();
                                                                            let len11 = vec11.len();
                                                                            ::core::mem::forget(vec11);
                                                                            *base
                                                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<usize>() = len11;
                                                                            *base
                                                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<*mut u8>() = ptr11.cast_mut();
                                                                        }
                                                                        None => {
                                                                            *base
                                                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<u8>() = (0i32) as u8;
                                                                        }
                                                                    };
                                                                }
                                                                V12::CommandSubst(e) => {
                                                                    *base.add(0).cast::<u8>() = (2i32) as u8;
                                                                    *base
                                                                        .add(::core::mem::size_of::<*const u8>())
                                                                        .cast::<i32>() = _rt::as_i32(e);
                                                                }
                                                            }
                                                        }
                                                    }
                                                    *base
                                                        .add(::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>() = len13;
                                                    *base.add(0).cast::<*mut u8>() = result13;
                                                }
                                            }
                                            *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len14;
                                            *base.add(0).cast::<*mut u8>() = result14;
                                            let vec23 = redirects6;
                                            let len23 = vec23.len();
                                            let layout23 = _rt::alloc::Layout::from_size_align_unchecked(
                                                vec23.len() * (3 * ::core::mem::size_of::<*const u8>()),
                                                ::core::mem::size_of::<*const u8>(),
                                            );
                                            let result23 = if layout23.size() != 0 {
                                                let ptr = _rt::alloc::alloc(layout23).cast::<u8>();
                                                if ptr.is_null() {
                                                    _rt::alloc::handle_alloc_error(layout23);
                                                }
                                                ptr
                                            } else {
                                                ::core::ptr::null_mut()
                                            };
                                            for (i, e) in vec23.into_iter().enumerate() {
                                                let base = result23
                                                    .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                                                {
                                                    let super::super::super::super::uzimaru::shell::types::Redirect {
                                                        kind: kind15,
                                                        target: target15,
                                                    } = e;
                                                    *base.add(0).cast::<u8>() = (kind15.clone() as i32) as u8;
                                                    let super::super::super::super::uzimaru::shell::types::ParsedWord {
                                                        segments: segments16,
                                                    } = target15;
                                                    let vec22 = segments16;
                                                    let len22 = vec22.len();
                                                    let layout22 = _rt::alloc::Layout::from_size_align_unchecked(
                                                        vec22.len() * (6 * ::core::mem::size_of::<*const u8>()),
                                                        ::core::mem::size_of::<*const u8>(),
                                                    );
                                                    let result22 = if layout22.size() != 0 {
                                                        let ptr = _rt::alloc::alloc(layout22).cast::<u8>();
                                                        if ptr.is_null() {
                                                            _rt::alloc::handle_alloc_error(layout22);
                                                        }
                                                        ptr
                                                    } else {
                                                        ::core::ptr::null_mut()
                                                    };
                                                    for (i, e) in vec22.into_iter().enumerate() {
                                                        let base = result22
                                                            .add(i * (6 * ::core::mem::size_of::<*const u8>()));
                                                        {
                                                            use super::super::super::super::uzimaru::shell::types::WordSegment as V21;
                                                            match e {
                                                                V21::Literal(e) => {
                                                                    *base.add(0).cast::<u8>() = (0i32) as u8;
                                                                    let vec17 = (e.into_bytes()).into_boxed_slice();
                                                                    let ptr17 = vec17.as_ptr().cast::<u8>();
                                                                    let len17 = vec17.len();
                                                                    ::core::mem::forget(vec17);
                                                                    *base
                                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                                        .cast::<usize>() = len17;
                                                                    *base
                                                                        .add(::core::mem::size_of::<*const u8>())
                                                                        .cast::<*mut u8>() = ptr17.cast_mut();
                                                                }
                                                                V21::EnvVar(e) => {
                                                                    *base.add(0).cast::<u8>() = (1i32) as u8;
                                                                    let super::super::super::super::uzimaru::shell::types::EnvRef {
                                                                        name: name18,
                                                                        default_value: default_value18,
                                                                    } = e;
                                                                    let vec19 = (name18.into_bytes()).into_boxed_slice();
                                                                    let ptr19 = vec19.as_ptr().cast::<u8>();
                                                                    let len19 = vec19.len();
                                                                    ::core::mem::forget(vec19);
                                                                    *base
                                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                                        .cast::<usize>() = len19;
                                                                    *base
                                                                        .add(::core::mem::size_of::<*const u8>())
                                                                        .cast::<*mut u8>() = ptr19.cast_mut();
                                                                    match default_value18 {
                                                                        Some(e) => {
                                                                            *base
                                                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<u8>() = (1i32) as u8;
                                                                            let vec20 = (e.into_bytes()).into_boxed_slice();
                                                                            let ptr20 = vec20.as_ptr().cast::<u8>();
                                                                            let len20 = vec20.len();
                                                                            ::core::mem::forget(vec20);
                                                                            *base
                                                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<usize>() = len20;
                                                                            *base
                                                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<*mut u8>() = ptr20.cast_mut();
                                                                        }
                                                                        None => {
                                                                            *base
                                                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<u8>() = (0i32) as u8;
                                                                        }
                                                                    };
                                                                }
                                                                V21::CommandSubst(e) => {
                                                                    *base.add(0).cast::<u8>() = (2i32) as u8;
                                                                    *base
                                                                        .add(::core::mem::size_of::<*const u8>())
                                                                        .cast::<i32>() = _rt::as_i32(e);
                                                                }
                                                            }
                                                        }
                                                    }
                                                    *base
                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>() = len22;
                                                    *base
                                                        .add(::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>() = result22;
                                                }
                                            }
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>() = len23;
                                            *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>() = result23;
                                        }
                                    }
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len24;
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = result24;
                                }
                            }
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len25;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result25;
                            let vec28 = substitutions3;
                            let len28 = vec28.len();
                            let layout28 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec28.len() * (3 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let result28 = if layout28.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout28).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout28);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec28.into_iter().enumerate() {
                                let base = result28
                                    .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let super::super::super::super::uzimaru::shell::types::CommandSubstitution {
                                        id: id26,
                                        input: input26,
                                    } = e;
                                    *base.add(0).cast::<i32>() = _rt::as_i32(id26);
                                    let vec27 = (input26.into_bytes()).into_boxed_slice();
                                    let ptr27 = vec27.as_ptr().cast::<u8>();
                                    let len27 = vec27.len();
                                    ::core::mem::forget(vec27);
                                    *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>() = len27;
                                    *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>() = ptr27.cast_mut();
                                }
                            }
                            *ptr2
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len28;
                            *ptr2
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = result28;
                        }
                        Err(e) => {
                            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::uzimaru::shell::types::ParseError {
                                message: message29,
                                position: position29,
                            } = e;
                            let vec30 = (message29.into_bytes()).into_boxed_slice();
                            let ptr30 = vec30.as_ptr().cast::<u8>();
                            let len30 = vec30.len();
                            ::core::mem::forget(vec30);
                            *ptr2
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len30;
                            *ptr2
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr30.cast_mut();
                            *ptr2
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(position29);
                        }
                    };
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_parse<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base34 = l1;
                            let len34 = l2;
                            for i in 0..len34 {
                                let base = base34
                                    .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l3 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l4 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    let base33 = l3;
                                    let len33 = l4;
                                    for i in 0..len33 {
                                        let base = base33
                                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                                        {
                                            let l5 = *base.add(0).cast::<*mut u8>();
                                            let l6 = *base
                                                .add(::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let base18 = l5;
                                            let len18 = l6;
                                            for i in 0..len18 {
                                                let base = base18
                                                    .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                                                {
                                                    let l7 = *base.add(0).cast::<*mut u8>();
                                                    let l8 = *base
                                                        .add(::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    let base17 = l7;
                                                    let len17 = l8;
                                                    for i in 0..len17 {
                                                        let base = base17
                                                            .add(i * (6 * ::core::mem::size_of::<*const u8>()));
                                                        {
                                                            let l9 = i32::from(*base.add(0).cast::<u8>());
                                                            match l9 {
                                                                0 => {
                                                                    let l10 = *base
                                                                        .add(::core::mem::size_of::<*const u8>())
                                                                        .cast::<*mut u8>();
                                                                    let l11 = *base
                                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                                        .cast::<usize>();
                                                                    _rt::cabi_dealloc(l10, l11, 1);
                                                                }
                                                                1 => {
                                                                    let l12 = *base
                                                                        .add(::core::mem::size_of::<*const u8>())
                                                                        .cast::<*mut u8>();
                                                                    let l13 = *base
                                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                                        .cast::<usize>();
                                                                    _rt::cabi_dealloc(l12, l13, 1);
                                                                    let l14 = i32::from(
                                                                        *base
                                                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                                                            .cast::<u8>(),
                                                                    );
                                                                    match l14 {
                                                                        0 => {}
                                                                        _ => {
                                                                            let l15 = *base
                                                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<*mut u8>();
                                                                            let l16 = *base
                                                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<usize>();
                                                                            _rt::cabi_dealloc(l15, l16, 1);
                                                                        }
                                                                    }
                                                                }
                                                                _ => {}
                                                            }
                                                        }
                                                    }
                                                    _rt::cabi_dealloc(
                                                        base17,
                                                        len17 * (6 * ::core::mem::size_of::<*const u8>()),
                                                        ::core::mem::size_of::<*const u8>(),
                                                    );
                                                }
                                            }
                                            _rt::cabi_dealloc(
                                                base18,
                                                len18 * (2 * ::core::mem::size_of::<*const u8>()),
                                                ::core::mem::size_of::<*const u8>(),
                                            );
                                            let l19 = *base
                                                .add(2 * ::core::mem::size_of::<*const u8>())
                                                .cast::<*mut u8>();
                                            let l20 = *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<usize>();
                                            let base32 = l19;
                                            let len32 = l20;
                                            for i in 0..len32 {
                                                let base = base32
                                                    .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                                                {
                                                    let l21 = *base
                                                        .add(::core::mem::size_of::<*const u8>())
                                                        .cast::<*mut u8>();
                                                    let l22 = *base
                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                        .cast::<usize>();
                                                    let base31 = l21;
                                                    let len31 = l22;
                                                    for i in 0..len31 {
                                                        let base = base31
                                                            .add(i * (6 * ::core::mem::size_of::<*const u8>()));
                                                        {
                                                            let l23 = i32::from(*base.add(0).cast::<u8>());
                                                            match l23 {
                                                                0 => {
                                                                    let l24 = *base
                                                                        .add(::core::mem::size_of::<*const u8>())
                                                                        .cast::<*mut u8>();
                                                                    let l25 = *base
                                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                                        .cast::<usize>();
                                                                    _rt::cabi_dealloc(l24, l25, 1);
                                                                }
                                                                1 => {
                                                                    let l26 = *base
                                                                        .add(::core::mem::size_of::<*const u8>())
                                                                        .cast::<*mut u8>();
                                                                    let l27 = *base
                                                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                                                        .cast::<usize>();
                                                                    _rt::cabi_dealloc(l26, l27, 1);
                                                                    let l28 = i32::from(
                                                                        *base
                                                                            .add(3 * ::core::mem::size_of::<*const u8>())
                                                                            .cast::<u8>(),
                                                                    );
                                                                    match l28 {
                                                                        0 => {}
                                                                        _ => {
                                                                            let l29 = *base
                                                                                .add(4 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<*mut u8>();
                                                                            let l30 = *base
                                                                                .add(5 * ::core::mem::size_of::<*const u8>())
                                                                                .cast::<usize>();
                                                                            _rt::cabi_dealloc(l29, l30, 1);
                                                                        }
                                                                    }
                                                                }
                                                                _ => {}
                                                            }
                                                        }
                                                    }
                                                    _rt::cabi_dealloc(
                                                        base31,
                                                        len31 * (6 * ::core::mem::size_of::<*const u8>()),
                                                        ::core::mem::size_of::<*const u8>(),
                                                    );
                                                }
                                            }
                                            _rt::cabi_dealloc(
                                                base32,
                                                len32 * (3 * ::core::mem::size_of::<*const u8>()),
                                                ::core::mem::size_of::<*const u8>(),
                                            );
                                        }
                                    }
                                    _rt::cabi_dealloc(
                                        base33,
                                        len33 * (4 * ::core::mem::size_of::<*const u8>()),
                                        ::core::mem::size_of::<*const u8>(),
                                    );
                                }
                            }
                            _rt::cabi_dealloc(
                                base34,
                                len34 * (3 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                            let l35 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l36 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base39 = l35;
                            let len39 = l36;
                            for i in 0..len39 {
                                let base = base39
                                    .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                                {
                                    let l37 = *base
                                        .add(::core::mem::size_of::<*const u8>())
                                        .cast::<*mut u8>();
                                    let l38 = *base
                                        .add(2 * ::core::mem::size_of::<*const u8>())
                                        .cast::<usize>();
                                    _rt::cabi_dealloc(l37, l38, 1);
                                }
                            }
                            _rt::cabi_dealloc(
                                base39,
                                len39 * (3 * ::core::mem::size_of::<*const u8>()),
                                ::core::mem::size_of::<*const u8>(),
                            );
                        }
                        _ => {
                            let l40 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l41 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l40, l41, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// コマンド文字列をパース
                    fn parse(input: _rt::String) -> Result<ParseResult, ParseError>;
                }
                #[doc(hidden)]
                macro_rules! __export_uzimaru_shell_parser_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "uzimaru:shell/parser#parse")] unsafe extern "C" fn
                        export_parse(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe
                        { $($path_to_types)*:: _export_parse_cabi::<$ty > (arg0, arg1) }
                        } #[unsafe (export_name =
                        "cabi_post_uzimaru:shell/parser#parse")] unsafe extern "C" fn
                        _post_return_parse(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_parse::<$ty > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_uzimaru_shell_parser_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 5 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 5
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod expander {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ParsedWord = super::super::super::super::uzimaru::shell::types::ParsedWord;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_expand_word_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let base13 = arg0;
                    let len13 = arg1;
                    let mut result13 = _rt::Vec::with_capacity(len13);
                    for i in 0..len13 {
                        let base = base13
                            .add(i * (6 * ::core::mem::size_of::<*const u8>()));
                        let e13 = {
                            let l0 = i32::from(*base.add(0).cast::<u8>());
                            use super::super::super::super::uzimaru::shell::types::WordSegment as V12;
                            let v12 = match l0 {
                                0 => {
                                    let e12 = {
                                        let l1 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l2 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len3 = l2;
                                        let bytes3 = _rt::Vec::from_raw_parts(
                                            l1.cast(),
                                            len3,
                                            len3,
                                        );
                                        _rt::string_lift(bytes3)
                                    };
                                    V12::Literal(e12)
                                }
                                1 => {
                                    let e12 = {
                                        let l4 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<*mut u8>();
                                        let l5 = *base
                                            .add(2 * ::core::mem::size_of::<*const u8>())
                                            .cast::<usize>();
                                        let len6 = l5;
                                        let bytes6 = _rt::Vec::from_raw_parts(
                                            l4.cast(),
                                            len6,
                                            len6,
                                        );
                                        let l7 = i32::from(
                                            *base
                                                .add(3 * ::core::mem::size_of::<*const u8>())
                                                .cast::<u8>(),
                                        );
                                        super::super::super::super::uzimaru::shell::types::EnvRef {
                                            name: _rt::string_lift(bytes6),
                                            default_value: match l7 {
                                                0 => None,
                                                1 => {
                                                    let e = {
                                                        let l8 = *base
                                                            .add(4 * ::core::mem::size_of::<*const u8>())
                                                            .cast::<*mut u8>();
                                                        let l9 = *base
                                                            .add(5 * ::core::mem::size_of::<*const u8>())
                                                            .cast::<usize>();
                                                        let len10 = l9;
                                                        let bytes10 = _rt::Vec::from_raw_parts(
                                                            l8.cast(),
                                                            len10,
                                                            len10,
                                                        );
                                                        _rt::string_lift(bytes10)
                                                    };
                                                    Some(e)
                                                }
                                                _ => _rt::invalid_enum_discriminant(),
                                            },
                                        }
                                    };
                                    V12::EnvVar(e12)
                                }
                                n => {
                                    debug_assert_eq!(n, 2, "invalid enum discriminant");
                                    let e12 = {
                                        let l11 = *base
                                            .add(::core::mem::size_of::<*const u8>())
                                            .cast::<i32>();
                                        l11 as u32
                                    };
                                    V12::CommandSubst(e12)
                                }
                            };
                            v12
                        };
                        result13.push(e13);
                    }
                    _rt::cabi_dealloc(
                        base13,
                        len13 * (6 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let base20 = arg2;
                    let len20 = arg3;
                    let mut result20 = _rt::Vec::with_capacity(len20);
                    for i in 0..len20 {
                        let base = base20
                            .add(i * (4 * ::core::mem::size_of::<*const u8>()));
                        let e20 = {
                            let l14 = *base.add(0).cast::<*mut u8>();
                            let l15 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len16 = l15;
                            let bytes16 = _rt::Vec::from_raw_parts(
                                l14.cast(),
                                len16,
                                len16,
                            );
                            let l17 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l18 = *base
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len19 = l18;
                            let bytes19 = _rt::Vec::from_raw_parts(
                                l17.cast(),
                                len19,
                                len19,
                            );
                            (_rt::string_lift(bytes16), _rt::string_lift(bytes19))
                        };
                        result20.push(e20);
                    }
                    _rt::cabi_dealloc(
                        base20,
                        len20 * (4 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result21 = T::expand_word(
                        super::super::super::super::uzimaru::shell::types::ParsedWord {
                            segments: result13,
                        },
                        result20,
                    );
                    let ptr22 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec23 = (result21.into_bytes()).into_boxed_slice();
                    let ptr23 = vec23.as_ptr().cast::<u8>();
                    let len23 = vec23.len();
                    ::core::mem::forget(vec23);
                    *ptr22.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len23;
                    *ptr22.add(0).cast::<*mut u8>() = ptr23.cast_mut();
                    ptr22
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_expand_word<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                pub trait Guest {
                    /// パース済みワードを展開
                    fn expand_word(
                        word: ParsedWord,
                        env: _rt::Vec<(_rt::String, _rt::String)>,
                    ) -> _rt::String;
                }
                #[doc(hidden)]
                macro_rules! __export_uzimaru_shell_expander_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "uzimaru:shell/expander#expand-word")] unsafe extern "C" fn
                        export_expand_word(arg0 : * mut u8, arg1 : usize, arg2 : * mut
                        u8, arg3 : usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_expand_word_cabi::<$ty > (arg0, arg1, arg2, arg3) } }
                        #[unsafe (export_name =
                        "cabi_post_uzimaru:shell/expander#expand-word")] unsafe extern
                        "C" fn _post_return_expand_word(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_expand_word::<$ty > (arg0) } }
                        };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_uzimaru_shell_expander_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_shell_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::uzimaru::shell::parser::__export_uzimaru_shell_parser_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::uzimaru::shell::parser);
        $($path_to_types_root)*::
        exports::uzimaru::shell::expander::__export_uzimaru_shell_expander_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::uzimaru::shell::expander);
    };
}
#[doc(inline)]
pub(crate) use __export_shell_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:uzimaru:shell:shell:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 922] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x9e\x06\x01A\x02\x01\
A\x09\x01B\x1f\x01ks\x01r\x02\x04names\x0ddefault-value\0\x04\0\x07env-ref\x03\0\
\x01\x01q\x03\x07literal\x01s\0\x07env-var\x01\x02\0\x0dcommand-subst\x01y\0\x04\
\0\x0cword-segment\x03\0\x03\x01p\x04\x01r\x01\x08segments\x05\x04\0\x0bparsed-w\
ord\x03\0\x06\x01m\x03\x05stdin\x06stdout\x0dstdout-append\x04\0\x0dredirect-kin\
d\x03\0\x08\x01r\x02\x04kind\x09\x06target\x07\x04\0\x08redirect\x03\0\x0a\x01p\x07\
\x01p\x0b\x01r\x02\x04args\x0c\x09redirects\x0d\x04\0\x0esimple-command\x03\0\x0e\
\x01p\x0f\x01r\x01\x08commands\x10\x04\0\x08pipeline\x03\0\x11\x01m\x03\x04none\x03\
and\x02or\x04\0\x09connector\x03\0\x13\x01r\x02\x09connector\x14\x08pipeline\x12\
\x04\0\x13conditional-element\x03\0\x15\x01r\x02\x02idy\x05inputs\x04\0\x14comma\
nd-substitution\x03\0\x17\x01p\x16\x01p\x18\x01r\x02\x08elements\x19\x0dsubstitu\
tions\x1a\x04\0\x0cparse-result\x03\0\x1b\x01r\x02\x07messages\x08positiony\x04\0\
\x0bparse-error\x03\0\x1d\x03\0\x13uzimaru:shell/types\x05\0\x02\x03\0\0\x0cpars\
e-result\x02\x03\0\0\x0bparse-error\x01B\x07\x02\x03\x02\x01\x01\x04\0\x0cparse-\
result\x03\0\0\x02\x03\x02\x01\x02\x04\0\x0bparse-error\x03\0\x02\x01j\x01\x01\x01\
\x03\x01@\x01\x05inputs\0\x04\x04\0\x05parse\x01\x05\x04\0\x14uzimaru:shell/pars\
er\x05\x03\x02\x03\0\0\x0bparsed-word\x01B\x06\x02\x03\x02\x01\x04\x04\0\x0bpars\
ed-word\x03\0\0\x01o\x02ss\x01p\x02\x01@\x02\x04word\x01\x03env\x03\0s\x04\0\x0b\
expand-word\x01\x04\x04\0\x16uzimaru:shell/expander\x05\x05\x04\0\x13uzimaru:she\
ll/shell\x04\0\x0b\x0b\x01\0\x05shell\x03\0\0\0G\x09producers\x01\x0cprocessed-b\
y\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
